import './style.css';
const root=document.querySelector('#app');
const glyphs=['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'];
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
let state=null,route=location.pathname,error='',busy=false,selectedMoment='',view='tropical';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const degrees=x=>`${Math.floor(x)}° ${String(Math.floor((x%1)*60)).padStart(2,'0')}′`;
const when=s=>new Date(s).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
const svgText=(x,y,text,cls='')=>`<text x="${x}" y="${y}" class="${cls}" text-anchor="middle" dominant-baseline="middle">${esc(text)}</text>`;
const colours={Conjunction:'#cfb56a',Sextile:'#3db8a0',Trine:'#3db8a0',Square:'#bb6c89',Opposition:'#bb6c89'};
function wheel(chart,transit=null){
 const asc=chart.ascendant;
 const pt=(deg,r)=>{let a=(180+asc-deg)*Math.PI/180;return [320+r*Math.cos(a),320-r*Math.sin(a)];};
 const line=(a,b,attrs='')=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" ${attrs}/>`;
 let s='<svg viewBox="-30 -30 700 700" role="img" aria-label="Western natal chart with exact longitude positions"><circle cx="320" cy="320" r="292" class="ring"/><circle cx="320" cy="320" r="243" class="ring"/><circle cx="320" cy="320" r="205" class="ring"/><circle cx="320" cy="320" r="128" class="ring"/>';
 for(let d=0;d<360;d++)s+=line(pt(d,292),pt(d,d%10===0?281:d%5===0?285:289),'class="tick"');
 for(let i=0;i<12;i++){s+=line(pt(i*30,243),pt(i*30,292),'class="division"');let p=pt(i*30+15,266);s+=svgText(...p,glyphs[i],'zodiac');s+=line(pt(chart.cusps[i],128),pt(chart.cusps[i],243),'class="house-line"');p=pt(chart.cusps[i]+15,188);s+=svgText(...p,i+1,'house-number');p=pt(i*30,305);s+=svgText(...p,`${i*30}°`,'degree-tick');}
 for(const a of chart.aspects){const p=chart.planets.find(p=>p.name===a.planet),q=chart.planets.find(p=>p.name===a.target);s+=line(pt(p.longitude,128),pt(q.longitude,128),`stroke="${colours[a.aspect]}" class="aspect"`);}
 let placed=[];
 chart.planets.forEach(p=>{let radius=224;while(placed.some(q=>Math.abs(((q.deg-p.longitude+540)%360)-180)<8&&Math.abs(q.r-radius)<20))radius-=26;placed.push({deg:p.longitude,r:radius});const tick=pt(p.longitude,243),end=pt(p.longitude,radius+10),label=pt(p.longitude,radius);s+=`<g><title>${esc(p.name)}: ${esc(p.sign)} ${degrees(p.degree)}${p.retrograde?' retrograde':''}</title>${line(tick,end,'class="planet-leader"')}${svgText(...label,p.glyph,'planet-glyph')}${svgText(...pt(p.longitude,radius-14),`${Math.floor(p.degree)}°${p.retrograde?' ℞':''}`,'planet-degree')}</g>`;});
 if(transit)for(const p of transit.planets){const q=pt(p.longitude,332);s+=`<g><title>Transit ${esc(p.name)} ${esc(p.sign)} ${degrees(p.degree)}</title>${line(pt(p.longitude,294),pt(p.longitude,320),'class="transit-line"')}${svgText(...q,p.glyph,'transit-glyph')}</g>`;}
 s+=line(pt(asc,126),pt(asc,296),'class="asc-line"');s+=svgText(...pt(asc,310),'ASC','asc-label');s+=svgText(320,305,'VELA','wheel-brand')+svgText(320,332,'YOUR NATAL SKY','wheel-caption');return s+'</svg>';
}
function vedic(chart){
 const cells=[[1,0],[2,0],[3,0],[3,1],[3,2],[3,3],[2,3],[1,3],[0,3],[0,2],[0,1],[0,0]];
 const asc=Math.floor(chart.ascendant/30);
 let s='<svg viewBox="0 0 640 640" role="img" aria-label="South Indian fixed sign chart, Lahiri sidereal"><rect x="24" y="24" width="592" height="592" rx="4" class="ring"/>';
 cells.forEach(([x,y],i)=>{const xx=24+x*148,yy=24+y*148;let planets=chart.planets.filter(p=>p.sign_index===i);s+=`<rect x="${xx}" y="${yy}" width="148" height="148" class="${i===asc?'lagna-cell':'vedic-cell'}"/>`;s+=svgText(xx+74,yy+18,`${signs[i]} · ${(i-asc+12)%12+1}`,'vedic-sign');if(i===asc)s+=svgText(xx+74,yy+36,'LAGNA','lagna-label');planets.forEach((p,j)=>{let py=yy+49+j*23;s+=svgText(xx+74,py,`${p.vedic_name} ${Math.floor(p.degree)}°${p.retrograde?' ℞':''}`,'vedic-planet');s+=svgText(xx+74,py+11,p.sanskrit,'vedic-sanskrit');});});
 s+=svgText(320,293,'SIDEREAL','wheel-brand')+svgText(320,326,'Lahiri ayanamsa','wheel-caption')+svgText(320,350,degrees(chart.ayanamsa),'vedic-planet');return s+'</svg>';
}
function panel(title,subtitle,body,cls=''){return `<section class="panel ${cls}"><div class="panel-heading"><div><h2>${title}</h2><p>${subtitle}</p></div></div>${body}</section>`;}
function table(planets,vedicMode=false,skyMode=false){return `<div class="table-scroll"><table><thead><tr><th>Planet</th><th>Sign</th><th>Degree</th><th>${skyMode?'Speed / day':'House'}</th><th>Motion</th></tr></thead><tbody>${planets.map(p=>`<tr><td><span class="table-glyph">${p.glyph}</span>${esc(vedicMode?p.vedic_name:p.name)}</td><td>${esc(p.sign)}</td><td>${degrees(p.degree)}</td><td>${skyMode?p.speed.toFixed(3)+'°':p.house}</td><td>${p.retrograde?'<span class="retro">Retrograde</span>':'<span class="direct">Direct</span>'}</td></tr>`).join('')}</tbody></table></div>`;}
function uncertainty(){const u=state.natal.uncertainty;return u?`<aside class="uncertainty"><span class="uncertainty-icon">◷</span><div><strong>Your birth time is approximate</strong><p>Using ${esc(state.profile.time)}, with a window of ±${u.minutes/60} hours. Tropical rising signs across samples: ${u.ascendants.tropical.join(', ')}. Sidereal: ${u.ascendants.sidereal.join(', ')}. Houses and timing remain provisional.</p><a href="/profile" data-nav>Review birth details ↗</a></div></aside>`:'';}
function eventsList(limit=200){let events=state.sky.events.slice(0,limit);return events.length?`<div class="events">${events.map(e=>`<article class="event"><span class="event-symbol">${e.kind.includes('eclipse')?'◐':e.kind==='Full moon'?'○':e.kind==='New moon'?'●':'✧'}</span><div><span class="eyebrow">${esc(e.system)}</span><h3>${esc(e.kind)}</h3><p>${esc(e.detail)}</p></div><time>${esc(when(e.at))}</time></article>`).join('')}</div>`:'<p class="empty">No events found in this window.</p>';}
function dashboard(){const retro=state.sky.tropical.planets.filter(p=>p.retrograde&&p.name!=='North node');const top=state.sky.transits[0];return `<div class="hero"><div><span class="eyebrow">TWO TRADITIONS. YOUR SKY.</span><h1>A little perspective.<br><em>A wider sky.</em></h1><p>Your charts and the moving sky, brought into one place.</p></div><div class="hero-orbit" aria-hidden="true"><span>✦</span></div></div><div class="metrics"><div class="metric"><span class="eyebrow">RETROGRADE NOW</span><strong>${retro.length}</strong><p>${retro.map(p=>p.name).join(', ')||'No planets retrograde'}</p></div><div class="metric"><span class="eyebrow">CLOSEST NATAL CONTACT</span><strong class="small">${top?esc(top.planet)+' '+top.aspect.toLowerCase():'No major contacts'}</strong><p>${top?esc(top.target)+' · '+top.orb.toFixed(2)+'° orb · '+top.phase:'Within the configured 3° orb'}</p></div><div class="metric"><span class="eyebrow">SOLAR PROXIMITY</span><strong class="small">${state.sky.cazimi.length?state.sky.cazimi.map(p=>p.planet).join(', '):'No cazimi detected'}</strong><p>Configured threshold: 17 arcminutes</p></div></div>${uncertainty()}<div class="chart-pair">${panel('The Western lens','Tropical · Whole sign houses',wheel(state.natal.tropical))}${panel('The Vedic lens','Lahiri sidereal · South Indian rāśi',vedic(state.natal.sidereal))}</div>${panel('On the horizon','Calculated events over the next 45 days',eventsList(5))}<div class="foundation"><span class="eyebrow">FIRST BUILD · CALCULATION FOUNDATION</span><h2>The sky first. Interpretation next.</h2><p>Your chart geometry is connected. Traditional knowledge, dasha calculations, AI conversation, friends and compatibility are upcoming stages. No generated readings are presented here.</p></div>`;}
function charts(){return `<h1>Your natal sky</h1><p class="intro">Two perspectives, calculated from the same birth details.</p>${uncertainty()}<div class="chart-pair">${panel('Western tropical','Whole sign · natal aspects use a 6° orb',wheel(state.natal.tropical))}${panel('Vedic sidereal','Lahiri · seven classical planets and mean lunar nodes',vedic(state.natal.sidereal))}</div><div class="chart-pair">${panel('Western placements','Provisional houses',table(state.natal.tropical.planets))}${panel('Vedic placements','Provisional whole sign houses',table(state.natal.sidereal.planets,true))}</div>${panel('Aspect key','Geometric contacts in the Western wheel',`<div class="aspect-key">${Object.entries(colours).map(([name,col])=>`<span><i style="background:${col}"></i>${name}</span>`).join('')}</div>`)}`;}
function transits(){const vedicPlanets=state.sky.sidereal.planets.map(p=>({...p,house:(p.sign_index-Math.floor(state.natal.sidereal.ascendant/30)+12)%12+1}));return `<h1>The moving sky</h1><p class="intro">${esc(when(state.sky.at))} · major transit contacts within 3°.</p><div class="toolbar"><label>Explore a moment <input id="moment" type="datetime-local" value="${esc(selectedMoment)}"></label><button id="explore">Calculate</button><button class="secondary" id="now">Return to now</button></div>${uncertainty()}<div class="transit-layout">${panel('Natal and current sky','Gold: natal · teal: transit',wheel(state.natal.tropical,state.sky.tropical))}${panel('Active natal contacts','Western geometric aspects. Not Vedic graha drishti.',`<div class="contacts">${state.sky.transits.slice(0,18).map(a=>`<article><span class="eyebrow">${a.phase} · ${a.orb.toFixed(2)}°</span><h3>${esc(a.planet)} <span>${a.aspect.toLowerCase()}</span> natal ${esc(a.target)}</h3></article>`).join('')||'<p>No major aspects within 3°.</p>'}</div>`)}</div><div class="chart-pair">${panel('Tropical positions','Longitude speed determines the motion indicator',table(state.sky.tropical.planets,false,true))}${panel('Sidereal positions','Houses counted from provisional natal lagna',table(vedicPlanets,true))}</div><p class="fine">${esc(state.sky.cazimi_rule)}</p>`;}
function profileForm(){const p=state?.profile||{name:'',date:'',time:'12:00',place:'',latitude:'',longitude:'',timezone:'Australia/Brisbane',uncertainty_minutes:0,time_source:''};return `<h1>Your birth details</h1><p class="intro">Saved on the local server. Never included in the public source.</p><form id="profile-form" class="profile-form panel"><div class="form-grid">${[['name','Name','text'],['date','Birth date','date'],['time','Provisional birth time','time'],['place','Birthplace','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['timezone','IANA time zone','text'],['uncertainty_minutes','Uncertainty either side, in minutes','number'],['time_source','Source of birth time','text']].map(([k,label,type])=>`<label>${label}<input name="${k}" type="${type}" value="${esc(p[k])}" ${type==='number'?'step="any"':''} required></label>`).join('')}</div><p class="fine">Use the town centre coordinates if the precise birth location is unknown. An unknown birth time is not yet supported by this foundation; do not enter an arbitrary time as confirmed.</p><button type="submit">Save and calculate</button><span id="form-status" role="status"></span></form>${state?panel('Birth time sensitivity','15 minute samples across your estimated window',`<p class="panel-copy">${state.natal.uncertainty?'Stable tropical sign placements across samples: '+state.natal.uncertainty.stable_signs.tropical.join(', ')+'. This is a sampled comparison, not a guarantee between samples.':'No uncertainty window has been entered.'}</p>`):''}`;}
function render(){let nav=[['/','Overview','◈'],['/chart','My charts','◎'],['/transits','Transits','↗'],['/calendar','Sky calendar','◷'],['/chat','AI conversation','✧'],['/profile','Birth profile','◇']];let body=state?(route==='/chart'?charts():route==='/transits'?transits():route==='/calendar'?`<h1>Your sky calendar</h1><p class="intro">Upcoming astronomical events and planetary changes. Times use your browser’s local zone.</p>${panel('The next 45 days','Eclipse times are global maxima, not local visibility times.',eventsList())}`:route==='/profile'?profileForm():route==='/chat'?`<h1>A conversation with context</h1><div class="foundation"><span class="eyebrow">NEXT MILESTONE</span><h2>Knowledge before answers.</h2><p>The AI conversation is not connected yet. It will use your calculated charts, current sky and separately sourced Western and Vedic teachings. There is no simulated chat in this build.</p></div>`:dashboard()):route==='/profile'?profileForm():`<h1>Your sky begins here</h1><p class="intro">Save your birth details once to open both charts.</p><a href="/profile" class="button" data-nav>Create your birth profile</a>`;
root.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="/" data-nav><span>✦</span> vela<span class="brand-dot">.</span></a><p class="brand-tag">A wider perspective</p><nav>${nav.map(([path,label,icon])=>`<a href="${path}" data-nav class="${route===path?'active':''}" ${route===path?'aria-current="page"':''}><span>${icon}</span>${label}${path==='/chat'?'<small>SOON</small>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><span class="status-dot"></span>First light<span>Calculation foundation</span></div></aside><div class="main-shell"><header><span>YOUR PERSONAL OBSERVATORY</span><div><span class="header-name">${esc(state?.profile.name||'Welcome')}</span><button class="secondary compact" id="refresh" ${busy?'disabled':''}>${busy?'Calculating…':'Refresh sky ↻'}</button></div></header><main>${error?`<div class="error" role="alert">${esc(error)} <button id="retry">Try again</button></div>`:''}${busy&&!state?'<p class="loading" role="status">Calculating your charts and upcoming events…</p>':body}</main><footer>Calculated with Swiss Ephemeris · Moshier · <a href="https://www.astro.com/swisseph/swephprg.htm" target="_blank" rel="noopener">Calculation reference ↗</a><span>Interpretation foundation pending review</span></footer></div></div>`;
root.querySelectorAll('[data-nav]').forEach(a=>a.onclick=e=>{e.preventDefault();route=a.getAttribute('href');history.pushState({},'',route);render();window.scrollTo(0,0);});
for(const id of ['refresh','retry','now']){const b=document.getElementById(id);if(b)b.onclick=()=>{selectedMoment='';load();};}
const exp=document.getElementById('explore');if(exp)exp.onclick=()=>{selectedMoment=document.getElementById('moment').value;if(!selectedMoment){error='Choose a date and time to explore.';render();return;}load(new Date(selectedMoment).toISOString());};
const form=document.getElementById('profile-form');if(form)form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));for(const k of ['latitude','longitude','uncertainty_minutes'])data[k]=Number(data[k]);try{await api('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});route='/';history.pushState({},'','/');await load();}catch(e){error=e.message;render();}};
}
async function api(path,options={}){const r=await fetch(path,options);if(!r.ok){let message='The calculation service could not complete this request.';try{const data=await r.json();if(typeof data.detail==='string')message=data.detail;else if(Array.isArray(data.detail))message='Please check your birth details, coordinates and time zone.';}catch{}throw new Error(message);}return r.json();}
async function load(at=''){busy=true;error='';render();try{const p=await api('/api/profile');if(p)state=await api('/api/workspace'+(at?'?at='+encodeURIComponent(at):''));else state=null;}catch(e){error=e instanceof TypeError?'The calculation service is unavailable. Start the backend and try again.':e.message;}finally{busy=false;render();}}
window.addEventListener('popstate',()=>{route=location.pathname;render();});
load();
